//! Rust generation.
//!
//! - `code` — one `<namespace>.rs` per schema: serde data types, C-like enums,
//!   and, per `protocol`, the full RPC shape (params structs, error enums, a
//!   provider trait, a `Dispatch` impl, and a `Client`-backed stub) against
//!   `comline-runtime`'s surface-4 contract.
//! - `lib` — a buildable crate: `Cargo.toml` + `src/lib.rs` (the `pub mod`
//!   tree) + `src/<namespace>.rs`. See design/generation.md.

use std::collections::HashMap;
use std::path::PathBuf;

use comline_core::schema::ir::compiler::interpreted::kind_search::KindValue;
use comline_core::schema::ir::frozen::unit::{FrozenArgument, FrozenUnit};

use eyre::{bail, Result};

use comline_codegen::{GenRequest, GeneratedFile, Mode, PackageMeta};

/// `comline-runtime` — the crate the generated RPC code links against. Pinned
/// by git rev (no crates.io yet); see design/runtime-repo-structure.md.
const RUNTIME_GIT: &str = "https://github.com/ComlineProject/runtime";
const RUNTIME_REV: &str = "0501812f57817d7b11165bc6a24f54afa45acb16";

pub fn generate_rust(req: &GenRequest) -> Result<Vec<GeneratedFile>> {
    match req.mode {
        Mode::Code => Ok(req
            .schemas
            .iter()
            .map(|(namespace, units)| GeneratedFile {
                path: PathBuf::from(format!("{namespace}.rs")),
                contents: schema_source(units),
            })
            .collect()),

        Mode::Lib => {
            require_flat_namespaces(req.schemas)?;

            let has_protocol = req
                .schemas
                .iter()
                .any(|(_, units)| units.iter().any(|u| matches!(u, FrozenUnit::Protocol { .. })));

            let mut files = vec![
                GeneratedFile {
                    path: PathBuf::from("Cargo.toml"),
                    contents: cargo_toml(&req.package, has_protocol),
                },
                GeneratedFile {
                    path: PathBuf::from("src/lib.rs"),
                    contents: lib_rs(req.schemas),
                },
            ];
            for (namespace, units) in req.schemas {
                files.push(GeneratedFile {
                    path: PathBuf::from(format!("src/{namespace}.rs")),
                    contents: schema_source(units),
                });
            }
            Ok(files)
        }
    }
}

/// `lib` mode emits a flat `pub mod <namespace>;` list; a `/`-joined namespace
/// would need an intermediate module tree. Not built yet.
fn require_flat_namespaces(schemas: &[(String, Vec<FrozenUnit>)]) -> Result<()> {
    for (namespace, _) in schemas {
        if namespace.contains('/') {
            bail!(
                "rust lib mode does not support nested namespaces yet \
                 (namespace `{namespace}`)"
            );
        }
    }
    Ok(())
}

fn cargo_toml(pkg: &PackageMeta, has_protocol: bool) -> String {
    let mut deps = String::from("serde = { version = \"1\", features = [\"derive\"] }\n");
    if has_protocol {
        deps.push_str(&format!(
            "comline-runtime = {{ git = \"{RUNTIME_GIT}\", rev = \"{RUNTIME_REV}\" }}\n"
        ));
    }
    format!(
        "# Generated by Comline\n\
         [package]\n\
         name = \"{}\"\n\
         version = \"{}\"\n\
         edition = \"2021\"\n\
         # A schema namespace named `main` would otherwise be picked up as a\n\
         # binary target (`src/main.rs`) with no `fn main`.\n\
         autobins = false\n\
         \n\
         [dependencies]\n\
         {deps}",
        pkg.name, pkg.version
    )
}

fn lib_rs(schemas: &[(String, Vec<FrozenUnit>)]) -> String {
    let mut s = String::from("// Generated by Comline\n\n");
    for (namespace, _) in schemas {
        s.push_str(&format!("pub mod {namespace};\n"));
    }
    s
}

fn schema_source(units: &[FrozenUnit]) -> String {
    let has_protocol = units.iter().any(|u| matches!(u, FrozenUnit::Protocol { .. }));
    let errors = error_type_names(units);

    let mut output = String::new();
    output.push_str("// Generated by Comline\n");
    output.push_str("use serde::{Deserialize, Serialize};\n");
    if has_protocol {
        output.push_str(
            "use comline_runtime::client::Client;\n\
             use comline_runtime::contract::{\n    \
                 BufMut, CallError, Dispatch, Envelope, Kind, RuntimeError, WireFormat,\n\
             };\n\
             use comline_runtime::transport::Transport;\n",
        );
    }
    output.push('\n');

    for unit in units {
        match unit {
            FrozenUnit::Struct { name, fields, .. } => {
                output.push_str(&data_struct(name, fields));
            }
            FrozenUnit::Enum { name, variants, .. } => {
                output.push_str(&data_enum(name, variants));
            }
            FrozenUnit::Error { name, fields, .. } => {
                output.push_str(&error_struct(name, fields));
            }
            FrozenUnit::Protocol { name, functions, .. } => {
                output.push_str(&protocol(name, functions, &errors));
            }
            _ => {}
        }
    }

    output
}

// ── data types ─────────────────────────────────────────────────────────────

fn field_lines(fields: &[FrozenUnit]) -> String {
    let mut s = String::new();
    for field in fields {
        if let FrozenUnit::Field {
            name,
            kind_value,
            optional,
            ..
        } = field
        {
            let ty = rust_type(kind_value);
            let ty = if *optional { format!("Option<{ty}>") } else { ty };
            s.push_str(&format!("    pub {name}: {ty},\n"));
        }
    }
    s
}

fn data_struct(name: &str, fields: &[FrozenUnit]) -> String {
    format!(
        "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {name} {{\n{}}}\n\n",
        field_lines(fields)
    )
}

fn error_struct(name: &str, fields: &[FrozenUnit]) -> String {
    format!(
        "#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\npub struct {name} {{\n{}}}\n\n",
        field_lines(fields)
    )
}

fn data_enum(name: &str, variants: &[FrozenUnit]) -> String {
    let mut s = format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]\npub enum {name} {{\n"
    );
    for variant in variants {
        if let FrozenUnit::EnumVariant(kv, _) = variant {
            let variant_name = match kv {
                KindValue::EnumVariant(n, _) | KindValue::Namespaced(n, _) => n.clone(),
                _ => "Unknown".to_string(),
            };
            s.push_str(&format!("    {variant_name},\n"));
        }
    }
    s.push_str("}\n\n");
    s
}

// ── protocol ───────────────────────────────────────────────────────────────

/// Schema-global error ordinal → the Rust type name of its `error` struct.
fn error_type_names(units: &[FrozenUnit]) -> HashMap<u16, String> {
    units
        .iter()
        .filter_map(|u| match u {
            FrozenUnit::Error { ordinal, name, .. } => Some((*ordinal, name.clone())),
            _ => None,
        })
        .collect()
}

struct Arg {
    name: String,
    /// The type in the provider trait / client signatures (`&str`, `u32`, `Msg`).
    sig_ty: String,
    /// The type in the params struct — `&'a str` where `sig_ty` is `&str`,
    /// otherwise identical. The params struct decodes borrowed from the wire.
    field_ty: String,
}

impl Arg {
    fn borrows(&self) -> bool {
        self.field_ty.contains("'a")
    }
}

struct FnInfo {
    name: String,
    params_ty: Option<String>,
    /// Whether the params struct needs a `<'a>` (any `&str` arg).
    params_borrows: bool,
    args: Vec<Arg>,
    ret: String,
    err_ty: String,
    /// `(ordinal, error struct type)` for each `!` on this function.
    throws: Vec<(u16, String)>,
    /// `_return: None` — fire-and-forget: `Client::notify`, the dispatcher
    /// writes no envelope, the trait method returns `()` with no error. An
    /// explicit `-> ()` (`KindValue::Unit`) is *not* this — it's a normal
    /// request/response with an empty ack (§4.4).
    one_way: bool,
    /// `@timeout_ms = N` on the function — the client method calls
    /// `Client::call_with_timeout` with `Duration::from_millis(N)`.
    timeout_ms: Option<u64>,
}

fn protocol(proto: &str, functions: &[FrozenUnit], errors: &HashMap<u16, String>) -> String {
    let fns: Vec<FnInfo> = functions
        .iter()
        .filter_map(|f| match f {
            FrozenUnit::Function {
                name,
                parameters,
                arguments,
                _return,
                throws,
                ..
            } => Some(fn_info(
                proto, name, parameters, arguments, _return, throws, errors,
            )),
            _ => None,
        })
        .collect();

    let mut s = String::new();

    // 1. params struct per function that takes arguments
    for f in &fns {
        if let Some(ty) = &f.params_ty {
            let lt = if f.params_borrows { "<'a>" } else { "" };
            s.push_str(&format!(
                "#[derive(Debug, Clone, Serialize, Deserialize)]\npub struct {ty}{lt} {{\n"
            ));
            for arg in &f.args {
                if arg.borrows() {
                    s.push_str("    #[serde(borrow)]\n");
                }
                s.push_str(&format!("    pub {}: {},\n", arg.name, arg.field_ty));
            }
            s.push_str("}\n\n");
        }
    }

    // 2. one schema-only error enum per request/response function (empty when
    //    it throws nothing). One-way functions have no error channel.
    for f in &fns {
        if f.one_way {
            continue;
        }
        s.push_str(&format!(
            "#[derive(Debug, Clone, PartialEq)]\npub enum {} {{\n",
            f.err_ty
        ));
        for (_, err) in &f.throws {
            s.push_str(&format!("    {err}({err}),\n"));
        }
        s.push_str("}\n\n");
    }

    // 2b. per-protocol union of every `!`, additive, for one broad handler
    let mut union: Vec<(u16, String)> = fns.iter().flat_map(|f| f.throws.clone()).collect();
    union.sort_by_key(|(ord, _)| *ord);
    union.dedup_by_key(|(ord, _)| *ord);
    let union_ty = format!("{proto}Error");
    s.push_str(&format!(
        "#[derive(Debug, Clone, PartialEq)]\npub enum {union_ty} {{\n"
    ));
    for (_, err) in &union {
        s.push_str(&format!("    {err}({err}),\n"));
    }
    s.push_str("}\n\n");
    for f in &fns {
        if f.throws.is_empty() {
            continue;
        }
        s.push_str(&format!(
            "impl From<{0}> for {union_ty} {{\n    fn from(e: {0}) -> Self {{\n        match e {{\n",
            f.err_ty
        ));
        for (_, err) in &f.throws {
            s.push_str(&format!(
                "            {}::{err}(x) => {union_ty}::{err}(x),\n",
                f.err_ty
            ));
        }
        s.push_str("        }\n    }\n}\n\n");
    }

    // 3. provider trait + the call table
    s.push_str(&format!("pub trait {proto} {{\n"));
    for f in &fns {
        let args = sig_args(&f.args);
        if f.one_way {
            s.push_str(&format!("    fn {}(&self{args});\n", f.name));
        } else {
            s.push_str(&format!(
                "    fn {}(&self{args}) -> Result<{}, {}>;\n",
                f.name, f.ret, f.err_ty
            ));
        }
    }
    s.push_str("}\n\n");

    let calls_const = format!("{}_CALLS", screaming(proto));
    s.push_str(&format!(
        "pub const {calls_const}: &[&str] = &[{}];\n\n",
        fns.iter()
            .map(|f| format!("\"{}\"", f.name))
            .collect::<Vec<_>>()
            .join(", ")
    ));

    // 4. dispatcher — implements the runtime `Dispatch` trait
    let mut l: Vec<String> = Vec::new();
    l.push(format!("pub struct {proto}Dispatcher<S>(pub S);"));
    l.push(String::new());
    // `out` is only written by request/response arms; a protocol that is
    // entirely one-way never touches it.
    let out_param = if fns.iter().all(|f| f.one_way) { "_out" } else { "out" };
    l.push(format!("impl<S: {proto}> Dispatch for {proto}Dispatcher<S> {{"));
    l.push("    fn dispatch<W: WireFormat>(".into());
    l.push("        &self,".into());
    l.push("        call: Kind,".into());
    l.push("        params: &[u8],".into());
    l.push("        fmt: &W,".into());
    l.push(format!("        {out_param}: &mut dyn BufMut,"));
    l.push("    ) -> Result<(), RuntimeError> {".into());
    l.push(format!(
        "        match call.resolve({calls_const}).ok_or(RuntimeError::UnknownCall)? {{"
    ));
    for (i, f) in fns.iter().enumerate() {
        l.push(format!("            {i} => {{"));
        let call_args = match &f.params_ty {
            Some(ty) => {
                l.push(format!("                let p: {ty} = fmt.decode(params)?;"));
                f.args
                    .iter()
                    .map(|a| format!("p.{}", a.name))
                    .collect::<Vec<_>>()
                    .join(", ")
            }
            None => {
                l.push("                let _: () = fmt.decode(params)?;".into());
                String::new()
            }
        };
        let call = format!("self.0.{}({call_args})", f.name);
        if f.one_way {
            // Run the handler; write no envelope — the `Server` sees the
            // empty buffer and replies with nothing.
            l.push(format!("                {call};"));
        } else {
            l.push(format!("                match {call} {{"));
            l.push("                    Ok(reply) => {".into());
            l.push("                        let mut body = Vec::new();".into());
            l.push("                        fmt.encode(&reply, &mut body)?;".into());
            l.push("                        Envelope::encode_ok(&body, out);".into());
            l.push("                    }".into());
            for (ord, err) in &f.throws {
                l.push(format!("                    Err({}::{err}(e)) => {{", f.err_ty));
                l.push("                        let mut body = Vec::new();".into());
                l.push("                        fmt.encode(&e, &mut body)?;".into());
                l.push(format!(
                    "                        Envelope::encode_err({ord}u16, &body, out);"
                ));
                l.push("                    }".into());
            }
            if f.throws.is_empty() {
                l.push("                    Err(never) => match never {},".into());
            }
            l.push("                }".into());
        }
        l.push("                Ok(())".into());
        l.push("            }".into());
    }
    l.push("            _ => Err(RuntimeError::UnknownCall),".into());
    l.push("        }".into());
    l.push("    }".into());
    l.push("}".into());
    l.push(String::new());
    l.push(String::new());
    s.push_str(&l.join("\n"));

    // 5. consumer stub — wraps a `Client`
    let mut l: Vec<String> = Vec::new();
    l.push(format!("pub struct {proto}Client<T, W>(pub Client<T, W>);"));
    l.push(String::new());
    l.push(format!(
        "impl<T: Transport, W: WireFormat> {proto}Client<T, W> {{"
    ));
    l.push("    pub fn new(client: Client<T, W>) -> Self {".into());
    l.push("        Self(client)".into());
    l.push("    }".into());
    for (i, f) in fns.iter().enumerate() {
        let args = sig_args(&f.args);
        let param_expr = match &f.params_ty {
            Some(ty) => {
                let init = f
                    .args
                    .iter()
                    .map(|a| a.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("&{ty} {{ {init} }}")
            }
            None => "&()".to_string(),
        };
        l.push(String::new());
        if f.one_way {
            // Fire-and-forget: no reply, so no `CallError<E>`.
            l.push(format!(
                "    pub fn {}(&mut self{args}) -> Result<(), RuntimeError> {{",
                f.name
            ));
            l.push(format!("        self.0.notify({i}u16, {param_expr})"));
            l.push("    }".into());
            continue;
        }
        l.push(format!(
            "    pub fn {}(&mut self{args}) -> Result<{}, CallError<{}>> {{",
            f.name, f.ret, f.err_ty
        ));
        let call = match f.timeout_ms {
            Some(ms) => format!(
                "self.0.call_with_timeout({i}u16, {param_expr}, core::time::Duration::from_millis({ms}))"
            ),
            None => format!("self.0.call({i}u16, {param_expr})"),
        };
        l.push(format!("        let (reply, fmt) = {call}?;"));
        l.push("        match reply {".into());
        l.push(
            "            Envelope::Ok(payload) => fmt.decode(payload).map_err(CallError::Runtime),"
                .into(),
        );
        for (ord, err) in &f.throws {
            l.push(format!("            Envelope::Err {{ id: {ord}u16, body }} => {{"));
            l.push(format!("                let e: {err} = fmt.decode(body)?;"));
            l.push(format!(
                "                Err(CallError::App({}::{err}(e)))",
                f.err_ty
            ));
            l.push("            }".into());
        }
        l.push(
            "            Envelope::Err { id, .. } => Err(CallError::Runtime(RuntimeError::Remote { id })),"
                .into(),
        );
        l.push("        }".into());
        l.push("    }".into());
    }
    l.push("}".into());
    l.push(String::new());
    l.push(String::new());
    s.push_str(&l.join("\n"));

    s
}

fn fn_info(
    proto: &str,
    name: &str,
    parameters: &[FrozenUnit],
    arguments: &[FrozenArgument],
    ret: &Option<KindValue>,
    throws: &[u16],
    errors: &HashMap<u16, String>,
) -> FnInfo {
    let pascal_fn = pascal(name);
    let timeout_ms = annotation(parameters, "timeout_ms").and_then(|v| v.parse::<u64>().ok());
    let args: Vec<Arg> = arguments
        .iter()
        .map(|a| {
            let (sig_ty, field_ty) = arg_types(&a.kind);
            Arg {
                name: a.name.clone(),
                sig_ty,
                field_ty,
            }
        })
        .collect();
    let params_borrows = args.iter().any(Arg::borrows);
    let params_ty = if args.is_empty() {
        None
    } else {
        Some(format!("{proto}{pascal_fn}Params"))
    };
    let one_way = ret.is_none();
    let ret = match ret {
        None | Some(KindValue::Unit) => "()".to_string(),
        Some(kv) => rust_type(kv),
    };
    // A one-way function carries no `!` (nowhere to deliver it); ignore any.
    let throws: &[u16] = if one_way { &[] } else { throws };
    let throws: Vec<(u16, String)> = throws
        .iter()
        .map(|ord| {
            (
                *ord,
                errors
                    .get(ord)
                    .cloned()
                    .unwrap_or_else(|| format!("UnknownError{ord}")),
            )
        })
        .collect();
    FnInfo {
        name: name.to_string(),
        params_ty,
        params_borrows,
        args,
        ret,
        err_ty: format!("{proto}{pascal_fn}Error"),
        throws,
        one_way,
        timeout_ms,
    }
}

/// The value of a scalar `@key = value` annotation (frozen as
/// `FrozenUnit::Property`), by key.
fn annotation<'a>(parameters: &'a [FrozenUnit], key: &str) -> Option<&'a str> {
    parameters.iter().find_map(|p| match p {
        FrozenUnit::Property { name, expression } if name == key => expression.as_deref(),
        _ => None,
    })
}

/// `(signature type, params-struct field type)` for a function argument.
/// A `str` / `string` arg is passed by reference and decoded borrowed from
/// the receive buffer; everything else is owned (borrowed arrays / nested
/// borrowed structs are a follow-up).
fn arg_types(kind: &KindValue) -> (String, String) {
    let owned = rust_type(kind);
    match owned.as_str() {
        "String" => ("&str".to_string(), "&'a str".to_string()),
        _ => (owned.clone(), owned),
    }
}

// ── name / type helpers ────────────────────────────────────────────────────

/// The `, name: ty, name: ty` suffix for a method taking `args` after `&self`
/// / `&mut self` — empty when there are none.
fn sig_args(args: &[Arg]) -> String {
    if args.is_empty() {
        return String::new();
    }
    let list = args
        .iter()
        .map(|a| format!("{}: {}", a.name, a.sig_ty))
        .collect::<Vec<_>>()
        .join(", ");
    format!(", {list}")
}

fn pascal(s: &str) -> String {
    s.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// `Chat` → `CHAT`, `UserService` → `USER_SERVICE`.
fn screaming(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.char_indices() {
        if c.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.extend(c.to_uppercase());
    }
    out
}

fn rust_type(kind: &KindValue) -> String {
    match kind {
        KindValue::Primitive(p) => map_str_type(p.name()),
        KindValue::Namespaced(name, _) => map_str_type(name),
        KindValue::EnumVariant(name, _) => name.clone(),
        KindValue::Unit => "()".to_string(),
        _ => "/* unknown_kind */".to_string(),
    }
}

fn map_str_type(s: &str) -> String {
    if let Some(inner) = s.strip_suffix("[]") {
        return format!("Vec<{}>", map_str_type(inner));
    }
    match s {
        "string" | "str" => "String".to_string(),
        "bool" => "bool".to_string(),
        "float" => "f64".to_string(),
        "int" => "i32".to_string(),
        "u8" | "u16" | "u32" | "u64" | "u128" => s.to_string(),
        // IDL spells signed integers with an `s` prefix (s8/s16/s32/s64);
        // Rust's own primitives are always `i`-prefixed, so this is a real
        // translation, not a passthrough.
        "s8" => "i8".to_string(),
        "s16" => "i16".to_string(),
        "s32" => "i32".to_string(),
        "s64" => "i64".to_string(),
        "s128" => "i128".to_string(),
        other => other.to_string(),
    }
}
